version: '2.4'
services:
  nginx:
    build:
      context: ./
      dockerfile: ngx.Dockerfile
    image: ngx:0.1
    depends_on:
      - php
    environment:
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /app
      NGINX_VHOST_PRESET: php
    ports:
      - "80:80"
    container_name: ngx
    working_dir: /app
    networks:
      - network

  #PHP Service
  php:
    build:
      context: ./
      dockerfile: php.Dockerfile
    image: php:0.1
    environment:
      DB_HOST: rm-xxx.mysql.rds.aliyuncs.com
      DB_PORT: 3306
      DB_NAME: db_name
      DB_USER: db_user
      DB_PASS: pass1234
      PHP_FPM_USER: php
      PHP_FPM_GROUP: php
      PHP_FPM_CLEAR_ENV: "no"
      PHP_DISPLAY_ERRORS: 0
      PHP_DISPLAY_STARTUP_ERRORS: 0
    container_name: php
    working_dir: /app
    networks:
      - network

#Docker Networks
networks:
  network:
    driver: bridge
